[package]
name = "hc_zome_rea_fulfillment_index"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
# :DUPE: hdk-rust-revid
hdk = "=0.0.40-alpha1"
hdk_proc_macros = "=0.0.40-alpha1"
holochain_wasm_utils = "=0.0.40-alpha1"
holochain_json_derive = "=0.0.17"

hdk_graph_helpers = { path = "../../../../../lib/hdk_graph_helpers" }
vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_economic_event_storage_consts = { path = "../../../../../lib/rea_economic_event/storage_consts" }
hc_zome_rea_fulfillment_storage_consts = { path = "../../../../../lib/rea_fulfillment/storage_consts" }
hc_zome_rea_fulfillment_storage = { path = "../../../../../lib/rea_fulfillment/storage" }
hc_zome_rea_fulfillment_rpc = { path = "../../../../../lib/rea_fulfillment/rpc" }
hc_zome_rea_fulfillment_lib = { path = "../../../../../lib/rea_fulfillment/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
