[package]
name = "hc_zome_rea_fulfillment_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.104"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
vf_measurement = { path = "../../../lib/vf_measurement" }
vf_actions = { path = "../../../lib/vf_actions" }
hc_zome_rea_fulfillment_rpc = { path = "../rpc" }

[lib]
crate-type = ["lib"]
