[package]
name = "hc_zome_rea_fulfillment"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "60a9062", package = "hdk3"}

hc_zome_rea_fulfillment_defs = { path = "../../../../../lib/rea_fulfillment/defs" }
hc_zome_rea_fulfillment_rpc = { path = "../../../../../lib/rea_fulfillment/rpc" }
hc_zome_rea_fulfillment_lib_origin = { path = "../../../../../lib/rea_fulfillment/lib_origin" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
