[workspace]

members= [
  "lib/hdk_graph_helpers",
  "lib/vf_core",
  "lib/vf_observation",
  "lib/vf_planning",
  "lib/vf_knowledge",
  "happs/observation/zomes/economic_event/code",
  "happs/observation/zomes/fulfillment/code",
  "happs/observation/zomes/satisfaction/code",
  "happs/observation/zomes/process/code",
  "happs/planning/zomes/commitment/code",
  "happs/planning/zomes/fulfillment/code",
  "happs/planning/zomes/intent/code",
  "happs/planning/zomes/satisfaction/code",
]
