[workspace]

members= [
  "lib/hdk_graph_helpers",
  "lib/vf_core",
  "lib/rea_economic_event/defs",
  "lib/rea_economic_event/lib",
  "lib/rea_economic_event/structs_internal",
  "lib/rea_economic_event/structs_rpc",
  "lib/rea_economic_resource/defs",
  "lib/rea_economic_resource/lib",
  "lib/rea_economic_resource/structs_internal",
  "lib/rea_economic_resource/structs_rpc",
  "lib/rea_process/defs",
  "lib/rea_process/lib",
  "lib/rea_process/structs_internal",
  "lib/rea_process/structs_rpc",
  "lib/vf_planning",
  "lib/vf_knowledge",
  "lib/vf_specification",
  "happs/observation/zomes/economic_event/code",
  "happs/observation/zomes/economic_resource/code",
  "happs/observation/zomes/fulfillment/code",
  "happs/observation/zomes/satisfaction/code",
  "happs/observation/zomes/process/code",
  "happs/planning/zomes/commitment/code",
  "happs/planning/zomes/fulfillment/code",
  "happs/planning/zomes/intent/code",
  "happs/planning/zomes/satisfaction/code",
  "happs/specification/zomes/resource_specification/code",
  "happs/specification/zomes/process_specification/code",
  "happs/specification/zomes/unit/code",
  "happs/specification/zomes/action/code",
]
