[workspace]

members= [
  "lib/hdk_graph_helpers",
  "lib/vf_core",
  "lib/vf_observation",
  "lib/vf_planning",
  "lib/vf_knowledge",
  "lib/vf_specification",
  "lib/vf_specification",
  "lib/vf_proposal",
  "happs/observation/zomes/economic_event/code",
  "happs/observation/zomes/economic_resource/code",
  "happs/observation/zomes/fulfillment/code",
  "happs/observation/zomes/satisfaction/code",
  "happs/observation/zomes/process/code",
  "happs/planning/zomes/commitment/code",
  "happs/planning/zomes/fulfillment/code",
  "happs/planning/zomes/intent/code",
  "happs/planning/zomes/satisfaction/code",
  "happs/specification/zomes/resource_specification/code",
  "happs/specification/zomes/process_specification/code",
  "happs/specification/zomes/unit/code",
  "happs/specification/zomes/action/code",
  "happs/proposal/zomes/proposal/code",
  "happs/proposal/zomes/proposed_intent/code",
  "happs/proposal/zomes/proposed_to/code",
]
