#---------[ agents ]-----------

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScjbTh687sEhwuizUKTAMI7CIdcjqyv9FWREyVssj7eqy8D9OSSUfDfazmu7z"
keystore_file = "./keyfile.agent1.txt"

#---------[ hApps ]-----------

[[dnas]]
id = "agent"
file = "./happs/agent/dist/agent.dna.json"
hash = ""
uuid = "vf_agent"

[[dnas]]
id = "observation"
file = "./happs/observation/dist/observation.dna.json"
hash = ""
uuid = "vf_obs"

[[dnas]]
id = "planning"
file = "./happs/planning/dist/planning.dna.json"
hash = ""
uuid = "vf_plan"

[[dnas]]
id = "proposal"
file = "./happs/proposal/dist/proposal.dna.json"
hash = ""
uuid = "vf_prop"

[[dnas]]
id = "specification"
file = "./happs/specification/dist/specification.dna.json"
hash = ""
uuid = "vf_spec"

[[instances]]
id = "agent"
agent = "test_agent1"
dna = "agent"

  [instances.storage]
  type = "memory"

[[instances]]
id = "observation"
agent = "test_agent1"
dna = "observation"

  [instances.storage]
  type = "memory"

[[instances]]
id = "planning"
agent = "test_agent1"
dna = "planning"
  [instances.storage]
  type = "memory"

[[instances]]
id = "proposal"
agent = "test_agent1"
dna = "proposal"
  [instances.storage]
  type = "memory"

[[instances]]
id = "specification"
agent = "test_agent1"
dna = "specification"

  [instances.storage]
  type = "memory"

[[bridges]]
caller_id = "planning"
callee_id = "observation"
handle = "vf_observation"

[[bridges]]
caller_id = "planning"
callee_id = "specification"
handle = "vf_specification"

[[bridges]]
caller_id = "observation"
callee_id = "specification"
handle = "vf_specification"

[[bridges]]
caller_id = "proposal"
callee_id = "planning"
handle = "vf_planning"

#---------[ gateway interfaces ]-----------

[[interfaces]]
id = "http_interface"
admin = true

  [interfaces.driver]
  type = "http"
  port = 4000

  [[interfaces.instances]]
  id = "agent"
  [[interfaces.instances]]
  id = "observation"
  [[interfaces.instances]]
  id = "planning"
  [[interfaces.instances]]
  id = "proposal"
  [[interfaces.instances]]
  id = "specification"

[[interfaces]]
id = "websocket_interface"
admin = true

  [interfaces.driver]
  type = "websocket"
  port = 4001

  [[interfaces.instances]]
  id = "agent"
  [[interfaces.instances]]
  id = "observation"
  [[interfaces.instances]]
  id = "planning"
  [[interfaces.instances]]
  id = "proposal"
  [[interfaces.instances]]
  id = "specification"

#---------[ misc ]-----------

[logger]
type = "debug"
