#---------[ agents ]-----------

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcSCJ4vtEsSWqtg8tmoK7tR4YvnHxa7ydYK6Oesxnrqgxq7xN4Kx5dHo3uQm58z"
keystore_file = "./keyfile.agent1.txt"

#---------[ hApps ]-----------

[[dnas]]
id = "HoloREA_dev"
file = "./happs/observation/dist/observation.dna.json"
hash = ""

[[instances]]
id = "test_instance1"
agent = "test_agent1"
dna = "HoloREA_dev"

  [instances.storage]
  type = "memory"

#---------[ gateway interfaces ]-----------

[[interfaces]]
id = "http_interface"
admin = true

  [interfaces.driver]
  type = "http"
  port = 4000

  [[interfaces.instances]]
  id = "test_instance1"

[[interfaces]]
id = "websocket_interface"
admin = true

  [interfaces.driver]
  type = "websocket"
  port = 3000

  [[interfaces.instances]]
  id = "test_instance1"

#---------[ misc ]-----------

[logger]
type = "debug"
