#---------[ agents ]-----------

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcSCizC4x4qV573n6yS4V6349cQQwFwh5uSVANZ4X86TiufmUqEGmF93kezkeur"
keystore_file = "./keyfile.agent1.txt"

#---------[ hApps ]-----------

[[dnas]]
id = "observation"
file = "./happs/observation/dist/observation.dna.json"
hash = ""

[[dnas]]
id = "planning"
file = "./happs/planning/dist/planning.dna.json"
hash = ""

[[instances]]
id = "a1_observation"
agent = "test_agent1"
dna = "observation"

  [instances.storage]
  type = "memory"

[[instances]]
id = "a1_planning"
agent = "test_agent1"
dna = "planning"

  [instances.storage]
  type = "memory"

[[bridges]]
caller_id = "a1_planning"
callee_id = "a1_observation"
handle = "vf_observation"

#---------[ gateway interfaces ]-----------

[[interfaces]]
id = "http_interface"
admin = true

  [interfaces.driver]
  type = "http"
  port = 4000

  [[interfaces.instances]]
  id = "a1_observation"
  [[interfaces.instances]]
  id = "a1_planning"

[[interfaces]]
id = "websocket_interface"
admin = true

  [interfaces.driver]
  type = "websocket"
  port = 4001

  [[interfaces.instances]]
  id = "a1_observation"
  [[interfaces.instances]]
  id = "a1_planning"

#---------[ misc ]-----------

[logger]
type = "debug"
