[package]
name = "hc_zome_rea_proposal_index_proposal"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.107"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_proposal_rpc = { path = "../rpc" }
hc_zome_rea_proposal_lib = { path = "../lib" }
hc_zome_rea_proposal_storage_consts = { path = "../storage_consts" }
hc_zome_rea_proposed_intent_storage_consts = { path = "../../rea_proposed_intent/storage_consts" }
hc_zome_rea_proposed_to_storage_consts = { path = "../../rea_proposed_to/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
