[package]
name = "hc_zome_rea_agreement_index_agreement"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.107"

hdk_records = { path = "../../../lib/hdk_records" }
hc_zome_rea_agreement_rpc = { path = "../rpc" }
hc_zome_rea_agreement_lib = { path = "../lib" }
hc_zome_rea_agreement_storage_consts = { path = "../storage_consts" }
hc_zome_rea_economic_event_storage_consts = { path = "../../rea_economic_event/storage_consts" }
hc_zome_rea_commitment_storage_consts = { path = "../../rea_commitment/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
