[package]
name = "hc_zome_rea_intent_index_planning"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.102"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_intent_rpc = { path = "../rpc" }
hc_zome_rea_intent_lib = { path = "../lib" }
hc_zome_rea_intent_storage_consts = { path = "../storage_consts" }
hc_zome_rea_satisfaction_storage_consts = { path = "../../rea_satisfaction/storage_consts" }
hc_zome_rea_process_storage_consts = { path = "../../rea_process/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
