[package]
name = "hc_zome_rea_intent_index_observation"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "ea8d62a4c", package = "hdk3"}

hdk_graph_helpers = { path = "../../../../lib/hdk_graph_helpers" }
vf_core = { path = "../../../../lib/vf_core" }
hc_zome_rea_intent_storage_consts = { path = "../../../../lib/rea_intent/storage_consts" }
hc_zome_rea_process_storage_consts = { path = "../../../../lib/rea_process/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
