[package]
name = "hc_zome_rea_proposed_intent_storage"
version = "0.1.0"
authors = ["Jhonatan Hern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.104"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_proposed_intent_rpc = { path = "../rpc" }

[lib]
crate-type = ["lib"]
