[package]
name = "hc_zome_rea_proposal_rpc"
version = "0.1.0"
authors = ["Jhonatan Hern <JhonatanHern@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }

[lib]
crate-type = ["lib"]
