[package]
name = "hc_zome_rea_intent_index_observation"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
# :DUPE: hdk-rust-revid
hdk = "0.0.104"

hdk_records = { path = "../../../../lib/hdk_records" }
vf_core = { path = "../../../../lib/vf_core" }
hc_zome_rea_intent_storage_consts = { path = "../../../../lib/rea_intent/storage_consts" }
hc_zome_rea_process_storage_consts = { path = "../../../../lib/rea_process/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
