[package]
name = "hc_zome_rea_agreement"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "ea8d62a4c", package = "hdk3"}

hc_zome_rea_agreement_storage = { path = "../../../../lib/rea_agreement/storage" }
hc_zome_rea_agreement_rpc = { path = "../../../../lib/rea_agreement/rpc" }
hc_zome_rea_agreement_lib = { path = "../../../../lib/rea_agreement/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
