[package]
name = "hc_zome_rea_process_index_planning"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "2eeec4a19", package = "hdk3"}

hc_zome_rea_commitment_storage_consts = { path = "../../../../../lib/rea_commitment/storage_consts" }
hc_zome_rea_intent_storage_consts = { path = "../../../../../lib/rea_intent/storage_consts" }
hc_zome_rea_process_storage_consts = { path = "../../../../../lib/rea_process/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
