[package]
name = "hc_zome_rea_economic_resource_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.108"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
vf_actions = { path = "../../../lib/vf_actions" }
vf_measurement = { path = "../../../lib/vf_measurement" }
hc_zome_rea_economic_resource_storage_consts = { path = "../storage_consts" }
hc_zome_rea_economic_resource_rpc = { path = "../rpc" }
hc_zome_rea_economic_event_storage = { path = "../../rea_economic_event/storage" }
hc_zome_rea_economic_event_rpc = { path = "../../rea_economic_event/rpc" }
hc_zome_rea_resource_specification_rpc = { path = "../../rea_resource_specification/rpc" }

[lib]
crate-type = ["lib"]
