[package]
name = "hc_zome_rea_fulfillment_lib_origin"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_fulfillment_storage_consts = { path = "../storage_consts" }
hc_zome_rea_fulfillment_storage = { path = "../storage" }
hc_zome_rea_fulfillment_rpc = { path = "../rpc" }
hc_zome_rea_fulfillment_lib = { path = "../lib" }

[lib]
crate-type = ["lib"]
