[package]
name = "hc_zome_rea_actions"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "0.0.104"

vf_actions = { path = "../../../../../lib/vf_actions" }
vf_core = { path = "../../../../../lib/vf_core" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
