[package]
name = "hc_zome_rea_proposal"
version = "0.1.0"
authors = ["JhonatanHern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "ea8d62a4c", package = "hdk3"}

hdk_graph_helpers = { path = "../../../../../lib/hdk_graph_helpers" }

vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_proposal_defs = { path = "../../../../../lib/rea_proposal/defs" }
hc_zome_rea_proposal_rpc = { path = "../../../../../lib/rea_proposal/rpc" }
hc_zome_rea_proposal_lib = { path = "../../../../../lib/rea_proposal/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
