[package]
name = "hc_zome_rea_satisfaction_index_observation"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "c6b3a4f0", package = "hdk3"}

hc_zome_rea_economic_event_storage_consts = { path = "../../../../../lib/rea_economic_event/storage_consts" }
hc_zome_rea_satisfaction_storage_consts = { path = "../../../../../lib/rea_satisfaction/storage_consts" }
hc_zome_rea_satisfaction_storage = { path = "../../../../../lib/rea_satisfaction/storage" }
hc_zome_rea_satisfaction_defs = { path = "../../../../../lib/rea_satisfaction/defs" }
hc_zome_rea_satisfaction_rpc = { path = "../../../../../lib/rea_satisfaction/rpc" }
hc_zome_rea_satisfaction_lib_destination = { path = "../../../../../lib/rea_satisfaction/lib_destination" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
