[package]
name = "hc_zome_rea_proposed_to"
version = "0.1.0"
authors = ["JhonatanHern <jhonatanhernandez998@gmail.com>", "pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.100"

vf_core = { path = "../../../../lib/vf_core" }
hdk_records = { path = "../../../../lib/hdk_records" }
hc_zome_rea_proposed_to_storage = { path = "../../../../lib/rea_proposed_to/storage" }
hc_zome_rea_proposed_to_rpc = { path = "../../../../lib/rea_proposed_to/rpc" }
hc_zome_rea_proposed_to_lib = { path = "../../../../lib/rea_proposed_to/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
