[package]
name = "hc_zome_rea_commitment"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
# :DUPE: hdk-rust-revid
hdk = "=0.0.42-alpha5"
hdk_proc_macros = "0.0.42-alpha5"

hc_zome_rea_commitment_defs = { path = "../../../../../lib/rea_commitment/defs" }
hc_zome_rea_commitment_rpc = { path = "../../../../../lib/rea_commitment/rpc" }
hc_zome_rea_commitment_lib = { path = "../../../../../lib/rea_commitment/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
