[package]
name = "hc_zome_rea_commitment"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "b881771", package = "hdk3"}

hc_zome_rea_commitment_defs = { path = "../../../../../lib/rea_commitment/defs" }
hc_zome_rea_commitment_rpc = { path = "../../../../../lib/rea_commitment/rpc" }
hc_zome_rea_commitment_lib = { path = "../../../../../lib/rea_commitment/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
