[package]
name = "hc_zome_rea_agent"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.102"

# hc_zome_rea_agent_defs = { path = "../../../../../lib/rea_agent/defs" }
hc_zome_rea_agent_rpc = { path = "../../../../../lib/rea_agent/rpc" }
# hc_zome_rea_agent_lib = { path = "../../../../../lib/rea_agent/lib" }

# hc_zome_agent_registration_storage = { path = "../../../../../thirdparty/happ-agent-registration/lib/storage" }
# hc_zome_agent_registration_lib = { path = "../../../../../thirdparty/happ-agent-registration/lib/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
