[package]
name = "hc_zome_rea_economic_resource_index_observation"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.108"

hdk_semantic_indexes_zome_lib = { path = "../../../lib/hdk_semantic_indexes/zome" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_economic_resource_rpc = { path = "../rpc" }
hc_zome_rea_economic_resource_lib = { path = "../lib" }
hc_zome_rea_economic_resource_storage_consts = { path = "../storage_consts" }
hc_zome_rea_economic_event_rpc = { path = "../../rea_economic_event/rpc" }
hc_zome_rea_economic_event_storage_consts = { path = "../../rea_economic_event/storage_consts" }
hc_zome_rea_resource_specification_storage_consts = { path = "../../rea_resource_specification/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
