[package]
name = "hc_zome_rea_process_specification"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/pospi/holochain", rev = "db6bc3b", package = "hdk3"}

vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_process_specification_defs = { path = "../../../../../lib/rea_process_specification/defs" }
hc_zome_rea_process_specification_rpc = { path = "../../../../../lib/rea_process_specification/rpc" }
hc_zome_rea_process_specification_lib = { path = "../../../../../lib/rea_process_specification/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
