[package]
name = "hc_zome_rea_commitment_index_agreement"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "2eeec4a19", package = "hdk3"}

hdk_graph_helpers = { path = "../../../../../lib/hdk_graph_helpers" }
hc_zome_rea_agreement_storage_consts = { path = "../../../../../lib/rea_agreement/storage_consts" }
hc_zome_rea_commitment_storage_consts = { path = "../../../../../lib/rea_commitment/storage_consts" }
vf_core = { path = "../../../../../lib/vf_core" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
