[package]
name = "hc_zome_dna_auth_resolver_hrea"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
hc_zome_dna_auth_resolver = {git = "https://github.com/steveeJ-forks/dna-auth-resolver", rev = "edf36795309e2d23734ee83e8d1c9903b16de7e5", package = "hc_zome_dna_auth_resolver"}

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
