[package]
name = "hc_zome_rea_unit"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "68a49be", package = "hdk3"}

vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_unit_defs = { path = "../../../../../lib/rea_unit/defs" }
hc_zome_rea_unit_rpc = { path = "../../../../../lib/rea_unit/rpc" }
hc_zome_rea_unit_lib = { path = "../../../../../lib/rea_unit/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
