[package]
name = "hc_zome_rea_proposed_to"
version = "0.1.0"
authors = ["JhonatanHern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk3 = {git = "https://github.com/holochain/holochain", rev = "39881a0", package = "hdk3"}

# hdk_graph_helpers = { path = "../../../../../lib/hdk_graph_helpers" }

vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_proposed_to_storage_consts = { path = "../../../../../lib/rea_proposed_to/storage_consts" }
hc_zome_rea_proposed_to_defs = { path = "../../../../../lib/rea_proposed_to/defs" }
hc_zome_rea_proposed_to_rpc = { path = "../../../../../lib/rea_proposed_to/rpc" }
hc_zome_rea_proposed_to_lib = { path = "../../../../../lib/rea_proposed_to/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
